### PR TITLE
Update requirements.txt

### LINKED ISSUE #4: bring back jupyterlab-fonts
[jupyterlab-fonts 2.0.0](https://pypi.org/project/jupyterlab-fonts/2.0.0/) is up. we can bring back some [styles from _fam](https://github.com/deathbeds/_fam/blob/07-11-2020/overrides.json#L52-L67) or rock some new stuff: some ideas for more accessible typography (which we could now more easily roll into the upstream if we like it):

- https://github.com/antijingoist/opendyslexic
  - appear to be a few CDN repackings
- https://brailleinstitute.org/freefont
  - on CDN: https://cdn.jsdelivr.net/npm/@fontsource/atkinson-hyperlegible@4.5.1/index.css
  - fontsource is _particularly_ interesting in that we could automate bringing/maintaining [_all_ of them](https://github.com/fontsource/fontsource/blob/main/FONTLIST.json) in, with proper licensing

### PR DESCRIPTION
**Pull request by tonyfast**
resolves #4 

anything else i need to do?

### CODE REVIEW

**Comment by bollwyvl** [comment]
What pretties we want to load up?

This is what `_fam` had before in `ovverides.json`:

```
  "@deathbeds/jupyterlab-fonts:fonts": {
    "styles": {
      "@import": [
        "https://tools-static.wmflabs.org/fontcdn/css?family=Libre+Baskerville:400,400italic,700&subset=latin,latin-ext"
      ],
      ":root": {
        "--jp-code-font-family": "'Fira Code Medium', var(--jp-code-font-family-default)",
        "--jp-content-font-family": "'Libre Baskerville', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
        "--jp-border-color0": "transparent",
        "--jp-border-color1": "transparent",
        "--jp-border-color2": "transparent",
        "--jp-cell-editor-border-color": "transparent",
        "--jp-toolbar-border-color": "transparent"
      }
    }
  }
```

**Comment by tonyfast** [comment]
oh shit, i didn't know we could do that!

**Comment by bollwyvl** [comment]
Yerp. If we wanted to try (an older) OpenDyslexic and trick out the terminal it'd be like:

```json
{
  "@deathbeds/jupyterlab-fonts:fonts": {
    "styles": {
      "@import": [
        "http://fonts.cdnfonts.com/css/opendyslexic"
      ],
      ":root": {
        "--jp-code-font-family": "OpenDyslexicMono, var(--jp-code-font-family-default)",
        "--jp-content-font-family": "OpenDyslexic, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'",
      }
    }
  },
  "@jupyterlab/terminal-extension:plugin": {
    "fontFamily": "OpenDyslexicMono, Menlo, Consolas, \"DejaVu Sans Mono\", monospace",
    "fontSize": 14
  }
}
```

**Comment by bollwyvl** [comment]
the `OpenDyslexic3` typeface (also available above) has a few additional glyph changes, like dotted zeros:

https://www.cdnfonts.com/opendyslexic.font

**Pull request merged**
